[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 921600
upload_protocol = teensy-gui
lib_deps = 
    tomstewart89/BasicLinearAlgebra @ ^4.3
    bblanchon/ArduinoJson @ ^6.21.5
    https://github.com/ftrias/TeensyThreads.git
build_flags = 
    -O3
    -ffast-math
    -DTEENSY_OPT_FASTEST
